variable "tags" {}
variable "env" {}
variable "subnets" {}
variable "vpc_id" {}
variable "sg_cidrs" {}
variable "rds_allocated_storage" {}
variable "rds_engine" {}
variable "rds_engine_version" {}
variable "rds_instance_class" {}
variable "kms" {}